server:
  port: 2333
  address: 0.0.0.0
  http2:
    enabled: false

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - ANDROID_VR
      - WEB
      - WEBEMBEDDED
      - TVHTML5_SIMPLY
      - TV
    oauth:
      enabled: true
    skipTrackOnError: true

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.2"
      snapshot: false
  server:
    password: ${LAVALINK_SERVER_PASSWORD}
    sources:
      youtube: false
      bandcamp: false
      soundcloud: true
      twitch: false
      vimeo: false
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    youtubePlaylistLoadLimit: 50
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    trackStuckThresholdMs: 10000
    resamplingQuality: MEDIUM
    opusEncodingQuality: 8
    useSeekGhosting: true

logging:
  file:
    path: ./logs/
  level:
    root: WARN
    lavalink: INFO
    dev.lavalink.youtube: INFO

  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 3
